# [v1.6.4] '알레르기 테스트' 버전
# 사용자의 날카로운 직감을 믿고, 의심스러운 'timeout = 25'를 잠시 격리 조치한다.
# 과연 진짜 범인이 맞을 것인가!

[build]
command = "npm install"
publish = "."

[functions]
directory = "netlify/functions/"
# timeout = 25 # <- 일단 주석 처리해서 기능을 잠시 비활성화!
node_bundler = "esbuild"
external_node_modules = ["node-fetch"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/sitemap.xml"
to = "/.netlify/functions/sitemap"
status = 200

