# [v1.6.5] '타임아웃 각인술' 최종 버전
# UI에 없으면 코드에 직접 새겨 넣는다! 'fetch-info' 요원에게 26초의 생명줄을 부여한다.

[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# 'fetch-info' 함수만을 위한 1:1 맞춤 설정
[functions."fetch-info"]
  # 이 함수의 작전 시간은 '26초'로 각인한다!
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200